# Generated by Django 4.2.2 on 2023-06-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=32)),
                ("last_name", models.CharField(max_length=32)),
                ("mobile_number", models.CharField(max_length=20)),
                ("start_date", models.DateField()),
                (
                    "position",
                    models.IntegerField(
                        choices=[
                            (1, "Junior Developer"),
                            (2, "Senior Developer"),
                            (3, "Team Lead"),
                            (4, "Project Manager"),
                            (5, "CEO"),
                        ]
                    ),
                ),
                (
                    "salary",
                    models.CharField(help_text="Salary with currency.", max_length=20),
                ),
                ("employee_id", models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
